image:
  repository: ghcr.io/example/casting-org
  tag: prod

env:
  CAST_ENV: production
  CAST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/casting_prod
  CAST_REDIS_URL: redis://redis:6379/2

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 2
    memory: 2Gi
