image:
  repository: ghcr.io/example/casting-org
  tag: staging

env:
  CAST_ENV: staging
  CAST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/casting_staging
  CAST_REDIS_URL: redis://redis:6379/1

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
