[project]
name = "casting-workspace"
version = "0.0.0"
description = "Workspace root for Casting monorepo"
requires-python = ">=3.13"
dependencies = []

# Do not install the root into the venv.
[tool.uv]
package = false
default-groups = ["dev"]

[tool.uv.workspace]
# Include general libs and apps; *exclude* orgs
members = ["apps/*", "libs/core", "libs/discord/framework", "libs/discord/processing", "libs/notion", "libs/obsidian", "libs/gcal"]
exclude = ["orgs/*"]

# Workspace-wide mapping: when a member depends on these names,
# satisfy them from the workspace (editable).
[tool.uv.sources]
casting-core = { workspace = true }
casting-discord-framework = { workspace = true }
casting-discord-processing = { workspace = true }
casting-notion = { workspace = true }
casting-obsidian = { workspace = true }
casting-gcal = { workspace = true }

[dependency-groups]
dev = [
  "pytest>=8",
  "pytest-asyncio>=0.23",
  "ruff>=0.5",
  "mypy>=1.10",
  "types-requests",
  "httpx>=0.27"
]