[project]
name = "casting-workspace"
version = "0.0.0"
description = "Workspace root for Casting monorepo"
requires-python = ">=3.13"
dependencies = []

# Do not install the root into the venv.
[tool.uv]
package = false
default-groups = ["dev"]

[tool.uv.workspace]
# Include general libs and apps; *exclude* orgs
members = [
    "apps/cast-explorer",
    "apps/prompt-gen",
    "apps/cast/cli",
    "apps/cast/tui",
    "apps/cast/server",
    "apps/cast/discord",
    "libs/core",
    "libs/discord/framework",
    "libs/discord/processing",
    "libs/notion",
    "libs/obsidian",
    "libs/gcal",
    "libs/cast/core",
    "libs/cast/sync",
    "libs/cast/git"
]
exclude = ["orgs/*"]

# Workspace-wide mapping: when a member depends on these names,
# satisfy them from the workspace (editable).
[tool.uv.sources]
casting-core = { workspace = true }
casting-discord-framework = { workspace = true }
casting-discord-processing = { workspace = true }
casting-notion = { workspace = true }
casting-obsidian = { workspace = true }
casting-gcal = { workspace = true }
cast-core = { workspace = true }
cast-sync = { workspace = true }
cast-git = { workspace = true }
cast-tui = { workspace = true }
cast-cli = { workspace = true }
cast-server = { workspace = true }
cast-discord = { workspace = true }

[dependency-groups]
dev = [
  "pytest>=8.3.0",
  "pytest-asyncio>=0.23",
  "ruff>=0.8.0",
  "pyright>=1.1.390",
  "mypy>=1.10",
  "types-requests",
  "httpx>=0.27",
  "poethepoet>=0.31.0",
  "ruamel.yaml>=0.18.0",
  "typer>=0.12.0"
]