image:
  repository: ghcr.io/example/casting-org
  tag: latest

service:
  port: 8000

env:
  CAST_ENV: dev
  CAST_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/casting_dev
  CAST_REDIS_URL: redis://redis:6379/0

resources: {}
