name: casting_org
version: 1.0.0
profile: casting_org
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  casting_org:
    +materialized: incremental
