
[project]
name = "cast-identity"
version = "0.1.0"
description = "Cast-Identity: resolve entity identities across applications (FastAPI + SQLAlchemy)"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Cast" }]
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "sqlalchemy>=2.0.30",
    "pydantic>=2.7.0",
    "pydantic-settings>=2.3.0",
    "alembic>=1.13.1",
    "psycopg[binary]>=3.2.0",
    "python-dotenv>=1.0.1",
    "typing-extensions>=4.11.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0",
    "pytest-asyncio>=0.23.7",
    "httpx>=0.27.0",
    "black>=24.4.2",
    "isort>=5.13.2",
    "ruff>=0.5.5",
]

[tool.black]
line-length = 100
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I"]
ignore = ["E402"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
